openapi: 3.0.1
info:
  title: FlightSearchAPI
  description: API Definition of FlightSearchAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/flightSearch
paths:
  /search:
    get:
      responses:
        default:
          description: Default response
